# Generated by Django 4.2.5 on 2023-09-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ditancab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='penyakit',
            name='gambar',
            field=models.ImageField(null=True, upload_to='penyakit/'),
        ),
    ]
